# Generated by Django 3.2.5 on 2021-12-08 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_rename_nivel_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, choices=[('RR.HH.', 'Recursos Humanos'), ('F', 'Finanzas'), ('Admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
