# Generated by Django 3.2.5 on 2021-12-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211208_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, choices=[('Recursos Humanos', 'Recursos Humanos'), ('Finanzas', 'Finanzas'), ('Admin', 'Admin'), ('Comun', 'Comun')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
    ]
