# Generated by Django 3.2.5 on 2021-12-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211208_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
    ]
