# Generated by Django 3.2.5 on 2021-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.CharField(blank=True, default='Activo', max_length=20),
        ),
    ]
