# Generated by Django 3.2.12 on 2022-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, choices=[('Recursos Humanos', 'Recursos Humanos'), ('Finanzas', 'Finanzas'), ('Admin', 'Admin'), ('Gerencia', 'Gerencia'), ('Comun', 'Comun')], max_length=20),
        ),
    ]
