# Generated by Django 3.2.5 on 2021-11-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_number', models.CharField(blank=True, max_length=20, verbose_name='Numero Antiguo')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Numero')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Nombre')),
                ('group', models.CharField(blank=True, max_length=30, verbose_name='Grupo')),
                ('team', models.CharField(blank=True, max_length=30, verbose_name='Equipo')),
                ('personal', models.CharField(blank=True, max_length=25, verbose_name='Personal')),
                ('department_rp', models.CharField(blank=True, max_length=30, verbose_name='Departamento RP')),
                ('area_rp', models.CharField(blank=True, max_length=30, verbose_name='Area RP')),
                ('position_rp', models.CharField(blank=True, max_length=2300, verbose_name='Puesto RP')),
                ('payroll', models.CharField(blank=True, max_length=20, verbose_name='Nómina')),
                ('admission_date', models.CharField(blank=True, max_length=20, verbose_name='ALTA')),
                ('antiquity', models.CharField(blank=True, max_length=20, verbose_name='Antiguedad')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Estatus')),
                ('leaving_date', models.CharField(blank=True, max_length=20, verbose_name='Fecha de Baja')),
                ('reason_of_leaving', models.CharField(blank=True, max_length=20, verbose_name='Causa de Baja')),
                ('curp', models.CharField(blank=True, max_length=20, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=20, verbose_name='RFC')),
                ('nss', models.CharField(blank=True, max_length=20, verbose_name='NSS')),
                ('age', models.CharField(blank=True, max_length=20, verbose_name='Edad')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Sexo')),
                ('department', models.CharField(blank=True, max_length=20, verbose_name='Departamento')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Puesto')),
                ('jacket', models.CharField(blank=True, max_length=20, verbose_name='Chaleco')),
                ('aplication', models.CharField(blank=True, max_length=20, verbose_name='Aplicación')),
                ('performance', models.CharField(blank=True, max_length=20, verbose_name='Rendimiento')),
                ('birth_date', models.CharField(blank=True, max_length=20, verbose_name='Fecha de Nacimiento')),
                ('nationality', models.CharField(blank=True, max_length=20, verbose_name='Nacionalidad')),
                ('place_of_birth', models.CharField(blank=True, max_length=20, verbose_name='Lugar de nacimiento')),
                ('municipality', models.CharField(blank=True, max_length=20, verbose_name='Municipio')),
                ('location', models.CharField(blank=True, max_length=20, verbose_name='Localidad')),
                ('division', models.CharField(blank=True, max_length=20, verbose_name='Fraccionamiento')),
                ('suburb', models.CharField(blank=True, max_length=20, verbose_name='Colonia')),
                ('street', models.CharField(blank=True, max_length=20, verbose_name='Calle')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Casa')),
                ('studies', models.CharField(blank=True, max_length=20, verbose_name='Estudios')),
                ('email', models.CharField(blank=True, max_length=20, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Télefono')),
                ('blood_type', models.CharField(blank=True, max_length=20, verbose_name='Tipo de Sangre')),
                ('allergies', models.CharField(blank=True, max_length=20, verbose_name='Alergias')),
                ('marital_status', models.CharField(blank=True, max_length=20, verbose_name='Estado Civil')),
                ('route', models.CharField(blank=True, max_length=20, verbose_name='Ruta')),
                ('bus_stop', models.CharField(blank=True, max_length=20, verbose_name='Parada')),
                ('emergency_phone_1', models.CharField(blank=True, max_length=20, verbose_name='Télefono de Emergencia 1')),
                ('emergency_phone_2', models.CharField(blank=True, max_length=20, verbose_name='Télefono de Emergencia 2')),
                ('emergency_phone_3', models.CharField(blank=True, max_length=20, verbose_name='Télefono de Emergencia 3')),
                ('schedule', models.CharField(blank=True, max_length=20, verbose_name='Horario')),
                ('number_of_children', models.CharField(blank=True, max_length=20, verbose_name='Número de Hijos')),
                ('age_of_kid_1', models.CharField(blank=True, max_length=20, verbose_name='Edad del hijo 1')),
                ('age_of_kid_2', models.CharField(blank=True, max_length=20, verbose_name='Edad del hijo 2')),
                ('age_of_kid_3', models.CharField(blank=True, max_length=20, verbose_name='Edad del hijo 3')),
                ('age_of_kid_4', models.CharField(blank=True, max_length=20, verbose_name='Edad del hijo 4')),
                ('age_of_kid_5', models.CharField(blank=True, max_length=20, verbose_name='Edad del hijo 5')),
                ('id_noi', models.CharField(blank=True, max_length=20, verbose_name='ID NOI')),
                ('boss_support', models.CharField(blank=True, max_length=20, verbose_name='Apoyo Jefe')),
                ('relation', models.CharField(blank=True, max_length=20, verbose_name='Relación')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
        ),
    ]
