# Generated by Django 3.2.5 on 2021-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='allergies',
            field=models.CharField(blank=True, max_length=60, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='antiquity',
            field=models.CharField(blank=True, max_length=30, verbose_name='Antiguedad'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='aplication',
            field=models.CharField(blank=True, max_length=30, verbose_name='Aplicación'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='blood_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo de Sangre'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='bus_stop',
            field=models.CharField(blank=True, max_length=40, verbose_name='Parada'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='curp',
            field=models.CharField(blank=True, max_length=40, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(blank=True, max_length=30, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='division',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fraccionamiento'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(blank=True, max_length=60, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emergency_phone_1',
            field=models.CharField(blank=True, max_length=35, verbose_name='Télefono de Emergencia 1'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emergency_phone_2',
            field=models.CharField(blank=True, max_length=35, verbose_name='Télefono de Emergencia 2'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emergency_phone_3',
            field=models.CharField(blank=True, max_length=35, verbose_name='Télefono de Emergencia 3'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='jacket',
            field=models.CharField(blank=True, max_length=30, verbose_name='Chaleco'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='municipality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nss',
            field=models.CharField(blank=True, max_length=30, verbose_name='NSS'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='performance',
            field=models.CharField(blank=True, max_length=30, verbose_name='Rendimiento'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Télefono'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(blank=True, max_length=30, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='reason_of_leaving',
            field=models.CharField(blank=True, max_length=50, verbose_name='Causa de Baja'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='relation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Relación'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rfc',
            field=models.CharField(blank=True, max_length=30, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='route',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='schedule',
            field=models.CharField(blank=True, max_length=25, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='studies',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='suburb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Colonia'),
        ),
    ]
