# Generated by Django 3.2.5 on 2021-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211119_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position_rp',
            field=models.CharField(blank=True, max_length=30, verbose_name='Puesto RP'),
        ),
    ]
