# Generated by Django 3.2.5 on 2021-11-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employees_position_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='jacket',
            field=models.CharField(blank=True, max_length=60, verbose_name='Chaleco'),
        ),
    ]
