# Generated by Django 3.2.5 on 2021-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employees_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='suburb',
            field=models.CharField(blank=True, max_length=130, verbose_name='Colonia'),
        ),
    ]
