# Generated by Django 3.2.5 on 2021-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employees_suburb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='area_rp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Area RP'),
        ),
    ]
