# Generated by Django 3.2.5 on 2021-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employees_area_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age_of_kid_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edad del hijo 1'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='age_of_kid_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edad del hijo 2'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='age_of_kid_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edad del hijo 3'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='age_of_kid_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edad del hijo 4'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='age_of_kid_5',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edad del hijo 5'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='number_of_children',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Hijos'),
        ),
    ]
