# Generated by Django 3.2.5 on 2021-12-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employees_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='schedule',
            field=models.IntegerField(blank=True, max_length=25, verbose_name='Horario'),
        ),
    ]
