# Generated by Django 3.2.5 on 2021-12-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employees_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20, verbose_name='Fecha')),
                ('time', models.CharField(blank=True, max_length=20, verbose_name='Hora')),
                ('number', models.CharField(blank=True, max_length=90, verbose_name='Numero empleado')),
                ('event', models.CharField(blank=True, max_length=20, verbose_name='Evento')),
                ('device', models.CharField(blank=True, max_length=60, verbose_name='Checador')),
                ('employee', models.CharField(blank=True, max_length=60, verbose_name='Master ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
        ),
    ]
