# Generated by Django 3.2.5 on 2022-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_incidences'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='minutes',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hours'),
        ),
    ]
