# Generated by Django 3.2.12 on 2022-04-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_incidences_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='age',
        ),
    ]
