# Generated by Django 3.2.12 on 2022-04-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_employees_e_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(blank=True, default='Activo', max_length=20, verbose_name='Estatus'),
        ),
    ]
