# Generated by Django 3.2.12 on 2022-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employees_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='clasification_taiwan',
            field=models.CharField(blank=True, max_length=50, verbose_name='Clasificacion Taiwan'),
        ),
        migrations.AddField(
            model_name='employees',
            name='habilities',
            field=models.CharField(blank=True, max_length=50, verbose_name='Habilidades'),
        ),
    ]
