# Generated by Django 3.2.12 on 2022-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_auto_20220408_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='clasification_taiwan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Clasificacion Taiwan'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position_rp',
            field=models.CharField(blank=True, max_length=150, verbose_name='Puesto RP'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='reason_of_leaving',
            field=models.CharField(blank=True, max_length=200, verbose_name='Causa de Baja'),
        ),
    ]
