# Generated by Django 3.2.12 on 2022-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_auto_20220408_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='turn',
            field=models.CharField(blank=True, max_length=150, verbose_name='Turno'),
        ),
    ]
