# Generated by Django 3.2.6 on 2022-01-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesphoto',
            name='name_photo',
        ),
    ]
