# Generated by Django 3.2.12 on 2022-02-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_remove_employeesphoto_name_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employeesPhoto',
        ),
    ]
