# Generated by Django 3.2.5 on 2021-12-09 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_ch', models.CharField(max_length=100, null=True, verbose_name='name_ch')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_ch', models.CharField(max_length=100, null=True, verbose_name='name_ch')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_ch', models.CharField(max_length=100, null=True, verbose_name='name_ch')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ch', models.CharField(max_length=100, null=True, verbose_name='name_ch')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
                ('description_ch', models.CharField(max_length=100, null=True, verbose_name='description_ch')),
                ('price', models.FloatField(verbose_name='price')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('no_producto', models.IntegerField(max_length=10, unique=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_shop.category')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_shop.shop')),
                ('unit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_shop.unit')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('amount', models.CharField(max_length=100, null=True, verbose_name='code')),
                ('unit', models.CharField(max_length=100, null=True, verbose_name='code')),
                ('product_name', models.CharField(max_length=100, null=True, verbose_name='code')),
                ('user_name', models.CharField(max_length=100, null=True, verbose_name='code')),
                ('unidad_cantidad', models.CharField(max_length=50, null=True)),
                ('unit_price', models.CharField(max_length=100, null=True, verbose_name='code')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-date'],
            },
        ),
    ]
