# Generated by Django 3.2.5 on 2021-12-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_master',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
