# Generated by Django 3.2.5 on 2021-12-17 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_shop', '0003_auto_20211209_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=100, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=100, null=True, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unidad_cantidad',
            field=models.CharField(max_length=50, null=True, verbose_name='unidad_cantidad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit',
            field=models.CharField(max_length=100, null=True, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.CharField(max_length=100, null=True, verbose_name='unit_price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='user_name'),
        ),
    ]
