# Generated by Django 3.2.5 on 2021-12-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_shop', '0004_auto_20211217_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, max_length=100, null=True, verbose_name='activo'),
        ),
    ]
