# Generated by Django 3.2.5 on 2021-12-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_shop', '0006_auto_20211220_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery_shop.product'),
        ),
    ]
