# Generated by Django 3.2.5 on 2021-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_shop', '0007_order_product_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_name',
            field=models.CharField(max_length=100, null=True, verbose_name='shop_name'),
        ),
    ]
