# Generated by Django 3.2.12 on 2022-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10, verbose_name='Número')),
                ('llave', models.CharField(default='0', max_length=15, verbose_name='llave')),
                ('cause', models.CharField(max_length=300, verbose_name='Causa')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='Diagnostico')),
                ('therapy', models.CharField(max_length=200, verbose_name='Tratamiento')),
                ('doctor', models.CharField(max_length=100, verbose_name='Doctor')),
                ('note', models.CharField(max_length=500, verbose_name='Nota')),
                ('extra', models.CharField(max_length=100, verbose_name='Extra')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(default='0', max_length=15, unique=True, verbose_name='llave')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=300, unique=True, verbose_name='Causa')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='Diagnostico')),
                ('therapy', models.CharField(max_length=200, verbose_name='Terapia')),
            ],
            options={
                'verbose_name': 'Diccionario',
                'verbose_name_plural': 'Diccionario',
            },
        ),
    ]
